# .github/workflows/bot-pr.yml
name: bot-create-pr

#######################################
# 3‑A Trigger – manual for first tests
#######################################
on:
  workflow_dispatch:                 # allows "Run workflow" button
    inputs:
      patch_b64:
        description: Base64‑encoded git diff
        required: true               # cannot start without a diff
# payload limit is 65 KB.  :contentReference[oaicite:4]{index=4}

#######################################
# 3‑B Token scopes inside the runner
#######################################
permissions:
  contents: write                    # allow commits & pushes :contentReference[oaicite:5]{index=5}
  pull-requests: write               # allow PR creation

jobs:
  apply-patch:
    runs-on: ubuntu-latest
    # optional safety: cancel older overlapping runs
    concurrency:
      group: bot-patch
      cancel-in-progress: true       # avoids race conditions :contentReference[oaicite:6]{index=6}

    steps:
    - uses: actions/checkout@v4      # fetch repo into workspace :contentReference[oaicite:7]{index=7}

    - name: Decode & apply patch
      run: |
        echo "${{ inputs.patch_b64 }}" | base64 -d > patch.diff
        git config --global user.name  "your-bot"
        git config --global user.email "bot@example.com"
        git checkout -b bot/patch-${{ github.run_id }}
        git apply patch.diff          # applies the diff :contentReference[oaicite:8]{index=8}
        git add -A
        git commit -m "bot patch ${{ github.run_id }}"

    - name: Push & open PR (via gh)
      env:
        GH_TOKEN: ${{ secrets.BOT_PAT }}  # bot’s PAT
      run: |
        git push -u origin HEAD
        gh pr create \                    # opens PR from current branch
          --title "Bot patch ${{ github.run_id }}" \
          --body  "Patch generated by workflow run ${{ github.run_id }}" \
          --label bot                     # optional label
# gh pr docs: :contentReference[oaicite:9]{index=9}
