name: bot-create-pr

on:
  workflow_dispatch:
    inputs:
      patch_b64:
        description: Base64‑encoded git diff
        required: true

permissions:
  contents: write          # git push ができる
  pull-requests: write     # PR 作成ができる

jobs:
  apply-patch:
    runs-on: ubuntu-latest
    concurrency:           # 同時実行の競合を防ぐ
      group: bot-patch
      cancel-in-progress: true

    steps:
      # ① リポジトリをチェックアウト
      - uses: actions/checkout@v4

      # ② パッチをデコードして適用
      - name: Decode & apply patch
        run: |
          echo "${{ inputs.patch_b64 }}" | base64 -d > patch.diff
          git config --global user.name  "your-bot"
          git config --global user.email "bot@example.com"
          git checkout -b bot/patch-${{ github.run_id }}
          git apply patch.diff
          git add -A
          git commit -m "bot patch ${{ github.run_id }}"

      # ③ ブランチを push → gh CLI で PR 作成
      #    gh はデフォルトで GITHUB_TOKEN を読み込む
      - name: Push & open PR
        run: |
          git push -u origin HEAD
          gh pr create --title "Bot patch ${{ github.run_id }}" --body "Automated patch from workflow run ${{ github.run_id }}" --label bot
